### ISSUE TITLE
Version and archived built versions

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-extensions-bundle#8]
## Problem

Right now it's hard to find out what are the versions of the different libraries that we've packaged with the bundle. Knowing which versions are bundled will let us trace what the deployment of the libraries and the expectations that we should regarding the deployment. This will help us more easily identify problems and bugs.

## Proposition

 - version the bundles
 - archive them in a branch `archive`
 - attach a file for each version describing the dependencies

**Comment by rayrutjes** [comment]
I would like to also state that bundling has a few cons:
- Increase the size of the JS files (we often load duplicated libs)
- makes it harder to customize the scripts
- makes it hard to re-use customizations across other websites that have no/different bundles
- hides the underlying libs in a way that we don't share properly the knowledge around those libs

The only advantage I see in bundling is avoiding conflicts with other scripts.
So far, the only conflict I have seen is 'autocomplete.js' conflicting with jquery-ui-autocomplete and google maps autocomplete.

If we rely on an external lib, then the user should ensure that lib is loaded prior to our JS files.
I think this is how most of the tools out there work and seems more pragmatic.
Not sure bundling is necessary because it adds yet another layer.

**Comment by bobylito** [comment]
@rayrutjes there is a major advantage to bundling, the dependencies are clearly identified and there is no problem with incompatible versions of our libraries (js client v2 and js helper v2). Once a bundle is validated for a given integration it is validated for all the integrations.

**Comment by rayrutjes** [comment]
@bobylito isn't this something that should be solved by semver + npm?

For me bundling = dependency management, but please prove me wrong, I feel like I'm missing something.

**Comment by bobylito** [comment]
@rayrutjes indeed it would be perfect to be able to rely on NPM for those. However, the bundle is mainly for CDN distributed implementations, no?

The bundle is like a linux distribution, it is said to be compliant and tested together. NPM only works at the package level.

**Comment by Haroenv** [comment]
I believe it's already bundled now
